baseURL = "https://gcappbesp307.health.dohmh.nycnet/dev-prod/"
[params]
    data_branch = "production"
    sub_URL = "/lookatmetoo/"

[caches]
    [caches.getresource]
      dir = ':cacheDir/:project'
      maxAge = 0