baseURL = "https://gcappbesp307.health.dohmh.nycnet/dev-stage/"
[params]
    data_branch = "feature-turn-off-charts"

[caches]
    [caches.getresource]
      dir = ':cacheDir/:project'
      maxAge = -1