baseURL = "https://gcappbesp307.health.dohmh.nycnet/dev-stage/"
[params]
    data_branch = "production-merge-2023-12"

[caches]
    [caches.getresource]
      dir = ':cacheDir/:project'
      maxAge = -1