baseURL = "https://gcappbesp307.health.dohmh.nycnet/IndicatorPublic/"
[params]
    # data_branch = "staging"
    data_branch = "feature-add-geos-to-comparisons"

[caches]
    [caches.getresource]
      dir = ':cacheDir/:project'
      maxAge = -1