
baseURL = "https://a816-dohbesp.nyc.gov/lookatme/"
[params]
    data_branch = "production"
    # sub_URL = "/IndicatorPublic/"
    sub_URL = "/lookatmetoo/"

[caches]
    [caches.getresource]
      dir = ':cacheDir/:project'
      maxAge = 0