baseURL = "http://gcappbesp307/IndicatorPublic/beta/"
[params]
    # sitepath = "/EH-dataportal"
    # data_branch = "staging"
    data_branch = "feature-add-geos-to-comparisons"

[caches]
    [caches.getresource]
      dir = ':cacheDir/:project'
      maxAge = -1