baseURL = "https://gcappbesp307.health.dohmh.nycnet/dev-test/beta/"
[params]
    data_branch = "feature-restructured-data"

[caches]
    [caches.getresource]
      dir = ':cacheDir/:project'
      maxAge = -1