name: Hugo Build to GitHub Pages [main]

# run action on a merged PR on development

on:
  push:
    branches: 
      - devcopy

jobs:
  nothing:
    name: Deploy Job [main]
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    # concurrency:
    #   group: ${{ github.workflow }}-${{ github.ref }}
